version: "3.8"

services:

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    restart: always
    environment:
      LDAP_ORGANISATION: "nectux"
      LDAP_DOMAIN: "nectux.com"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - keycloaknet

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
    ports:
      - "6443:80"
    networks:
      - keycloaknet
    depends_on:
      - openldap

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    restart: always
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8080:8080"
    networks:
      - keycloaknet
    depends_on:
      - openldap
      - postgres

  postgres:
    image: postgres:15
    container_name: postgresTax
    restart: always
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: taxCollect
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - keycloaknet


volumes:
  ldap_data:
  ldap_config:
  pg_data:


networks:
  keycloaknet:
