package com.nectuxingenieries.collect.tax.models.enums;

public enum TypeAnomalie {
    CONTRIBUABLE_INTROUVABLE,
    ACTIVITE_NON_DECLAREE,
    DOUBLON,
    MAUVAIS_SECTEUR,
    MONTANT_INCOHERENT,
    PAIEMENT_NON_RAPPROCHE,
    AGENT_ABSENT,
    CONTRIBUABLE_CONTESTATAIRE,
    MONTANT_CONTESTE,
    ACTIVITE_FERMEE,
    ERREUR_AFFECTATION,
    OPERATION_DOUTEUSE,
    AUTRE
}
