package com.nectuxingenieries.collect.tax.models.enums;

public enum TypeAudit {
    VISITE_CONTRIBUABLE,
    PAIEMENT_ENREGISTRE,
    RECU_GENERE,
    NOUVEAU_CONTRIBUABLE,
    SYNCHRONISATION,
    MODIFICATION,
    SUPPRESSION,
    CONNEXION,
    DECONNEXION,
    AFFECTATION_AGENT,
    RETRAIT_AGENT,
    AFFECTATION_RESPONSABLE,
    PROPOSITION_AFFECTATION,
    VALIDATION_PROPOSITION,
    REJET_PROPOSITION,
    ANOMALIE_CREE,
    ANOMALIE_TRANSMISE,
    ANOMALIE_CLOTURE,
    ANOMALIE_ESCALEE,
    OPERATION_DOUTEUSE,
    CHANGEMENT_STATUT_AGENT
}
